export default {
	PRIMARY_COLOR: '#0C8711',
	SECONDARY_COLOR: '#C9E0AD',
	FONT_SIZE_SMALL: 12,
	FONT_SIZE_MEDIUM: 16,
	FONT_SIZE_LARGE: 24,
	FONT_SIZE_TITLE: 24,
	FONT_WEIGHT_LIGHT: '200',
	FONT_WEIGHT_MEDIUM: '500',
	FONT_WEIGHT_BOLD: '700',
	BACKGROUND_COLOR_LIGHT: '#f0f6f8',
	BACKGROUND_COLOR_WHITE: '#ffffff',
	LIGHT_GRAY_COLOR: '#f0f3f3',
	DARK_GRAY_COLOR: '#444444',
	CONTAINER_PADDING: 20
};